In [1]:
import sys
sys.path.append("D:\\alexa\\Documents\\metal-fatigue")

In [47]:
import numpy as np
from metal_fatigue import rainfl
import imp
imp.reload(rainfl)

<module 'metal_fatigue.rainfl' from 'D:\\alexa\\Documents\\metal-fatigue\\metal_fatigue\\rainfl.py'>

## rfm class

In [14]:
#create counts matrix
coun = np.array([[3,1,0],[2,3.,5],[2e6,1,3012]])

#create some ybinsize and xbinsize for the rfm
xbins = 15.
ybins = 1.

testrfm = rainfl.rfm(xbins,ybins,coun)

print(testrfm.counts)
print(testrfm.xbinsize)
print(testrfm.ybinsize)

[[  3.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   3.00000000e+00   5.00000000e+00]
 [  2.00000000e+06   1.00000000e+00   3.01200000e+03]]
15.0
1.0


## consistency_check function

In [30]:
a = rainfl.rfm(3.,12,np.array([[1,2,3],[4,1,2]]))
b = rainfl.rfm(3,12.,np.array([[1,2,3],[4,1,2]]))
rainfl.consistency_check(a,b)

## add function

In [49]:
ca = np.array([[1,0,0],[0,1,2]])
cb = np.array([[1,2,3],[4,0,2.5]])
a = rainfl.rfm(3.,12,ca)
b = rainfl.rfm(3,12.,cb)

print(rainfl.add(a,b).counts)
print(ca+cb)

[[ 2.   2.   3. ]
 [ 4.   1.   4.5]]
[[ 2.   2.   3. ]
 [ 4.   1.   4.5]]
